# Site settings
# in the templates available like {{ site.myvariable }}.
title: Capturardor de momentos.
email: angycolorado@domain.com
brand: Angy Colorado
headline: Fotografía, Peliculas, Rodajes y Álbumes
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # Fotografía con Angy /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: 2016 Whatever Company, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: angycolorado@gmail.com
phone: +1-800-555-2016

# Tracking
googleAnalitycsID: UA-83933844-1

